import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Fredoka } from "next/font/google";
const fredoka = Fredoka({
  subsets: ["latin"],
  variable: "--font-fredoka",
});
// import { Spotlight } from "@/components/ui/spotlight";
import { EvervaultCard } from "@/components/ui/evervault-card";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fredoka.variable} antialiased dark:bg-black dark:text-[#f8fafc] bg-[#f1f5f9] text-[#020617] canva-effect`}
      >
        <EvervaultCard >

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        </EvervaultCard>
      </body>
    </html>
  );
}
